name=HomeShield.ESP.Core
version=1.1.0
author=Selvaganapathi Kasi
maintainer=Selvaganapathi Kasi
sentence=Core library for HomeShield ESP devices.
paragraph=BLE onboarding, WiFi, Registration and common services.
category=Communication
architectures=esp32
depends=NimBLE-Arduino, PubSubClient
