name=HomeShield.ESP.Core
version=1.0.0
author=Selvaganapathi Kasi
maintainer=Selvaganapathi Kasi
sentence=Core library for HomeShield ESP devices.
paragraph=Provisioning, WiFi, Registration and common services.
category=Communication
architectures=esp32